- Disney/DisneyBase.js
- Disney/DisneyTokyoBase.js
- README.md
- Scripts/UpdateREADME.js
- SeaWorld/SeaWorldBase.js
- SixFlags/SixFlagsBase.js
- Universal/UniversalBase.js
- parkBase.js
- test.js
See #13 
Going to investigate other park APIs for similar results. Will have to add some sort of function call or flag to each park API to confirm if they support returning ride schedules.
> Add ride opening times to wait time results

- Disney/DisneyTokyoBase.js
Hi,
I do some fix for the DisneylandTokyoBase lib of active should be true or false, and also add a new property named updateTime for tell us when the data update.
> Fix the Tokyo Disney active bug and add updateTime for waittime data effective time

- Universal/UniversalBase.js
Check for the odd occurrence when successful request to Universal but no data. 
As per issue #19
> Added check for no data after successful request for Universal

- Misc/AltonTowers.js
- index.js
Need to work out wait time format once park is open
> Add Alton Towers

- Disney/DisneyBase.js
- Disney/ShanghaiDisneyResort.js
- index.js
Not open yet, but still got a functional API :)
See #8
> Add Shanghai Disney Resort to API

- Misc/EuropaPark.js
Updating EuropaPark request and response
and fix for node v0.8
> EuropaPark implementation improved

- Misc/Asterix.js
- Misc/AsterixData.json
- index.js
First version of Asterix park (https://www.parcasterix.fr/)
Please note that the park is known to not have reliable waiting times. Use with caution :whale:
> Parc Asterix

- Misc/Asterix.js
Patch status when closing time is known; unfortunately, the ride status doesn't seems always updated after park closing time.
> Asterix : status patch

- lib/disney/index.js
Alter so ride active, status, and wait time report correctly.
> Improve Disney ride status

- lib/disney/index.js
Change the token cache expiry in to be less aggressive.
> Fix bug caused by variable shadowing

- lib/index.js
- lib/universal/universalstudiossingapore.js
This should add in wait times for Universal Studios Singapore. My Javascript knowledge is pretty basic, so let me know if there's any style fixes you would like.
> Universal Studios Singapore Wait Times

- lib/merlinparks/altontowers.js
I added Wicker Man, Alton Towers latest ride.
> Added Wicker Man

- lib/merlinparks/chessingtonworldofadventures_data.js
Chessington have 2 rides (The Gruffalo River Ride Adventure and The Chessington Adventure Tree) not in the older version of the file.
> Updated Chessington world of adventures data JSON

- README.md
- lib/herschend/dollywood.js
- lib/herschend/index.js
- lib/herschend/silverdollarcity.js
- lib/index.js
#83 
Wild Adventures doesn't seem to have support for wait times. The base class should make it super easy to add support for future Herschend Parks as long as they continue to use the same endpoint format.
> Support for Herschend Parks (Dollywood + Silver Dollar City)

- lib/disneytokyo/index.js
The Tokyo Disney API bumped their API version again, and this updates the code to match.
> Updates the API version number for Tokyo Disney resorts to resolve issue #122

- lib/efteling/index.js
The Efteling POI API will return "Update the app" data if you include the` x-api-key` and `x-api-version `headers.
> Fix Efteling POI API not working

- lib/disney/disneylandparismagickingdom.js
- lib/disney/disneylandpariswaltdisneystudios.js
#144 Fix this issue but probably more test requires because I only use GetWaitTimes on this park
> fix: #144 FetchFacilitiesURL for DisneylandParis

- lib/europapark/index.js
> Update Europa API Version

- lib/europapark/index.js
Bump Europa Park api to lastest version
> [~] Update Europa Park api

- lib/merlinparks/index.js
Fixes OpeningTime fetching error for AltonTowers and ThorpePark.
Side note: ThorpePark is still in error for waiting times.
> Fixes MerlinParks FetchOpeningTimes

- lib/hersheys/index.js
The Hershey Park opening times where always noted as "Closed" before this fix
> Fixes HersheyPark Opening Times

- lib/cedarfair/index.js
A query string of the schedule URL was preventing the call to the API to work
> Fixes Carowind Opening Times

- lib/merlinparks/altontowers.js
- lib/merlinparks/altontowers_data.json
- lib/merlinparks/index.js
- lib/merlinparks/thorpepark.js
- lib/merlinparks/thorpepark_data.json
- lib/schedule.js
- package-lock.json
- package.json
Lot of rework involved as the URL and content of the API of two parks is different.
Linked to cubehouse/themeparks#160
> Fixes the Merlin parks issues

- lib/europapark/index.js
Fixes cubehouse/themeparks#163
> EuropaPark opening times api-5.9

- lib/disney/index.js
- lib/disneytokyo/index.js
> Fix cubehouse/themeparks#169

- README.md
- lib/disney/disneylandparismagickingdom.js
- lib/disney/disneylandresortcaliforniaadventure.js
- lib/disney/disneylandresortmagickingdom.js
* Fix cubehouse/themeparks#186
* Update Readme
> Fix park names in v5

- lib/sixflags/sixflagsbase.js
Linked to issue cubehouse/themeparks#180
Does not close it as the returned ride wait time is always 0 when the ride is open and the park doesn't communicate waiting time.
The result return by themepark doesn't give this information to the user.
> Better ride status for SixFlags parks

- lib/asterixpark/asterixpark.js
- lib/sixflags/sixflagsbase.js
- lib/testonline.js
This example is linked to cubehouse/themeparks#180.
> Null as accepted value for ride.waitTime.

- lib/ride.js
- lib/test.js
> Fix #195 - Update lastUpdate when changing meta data

- lib/portaventura/portaventura.js
Default wait time = 'null' instead of '0'
Fixes #202
> PortAventura parks

- lib/seaworld/seaworldparkbase.js
+ Code simplified with the use of cheerio lib
> Fixes cubehouse/themeparks#206

- lib/disney/disneyworldapibase.js
Fixes #211 - null out fastPassStartTiem and fastPassEndTime when there are no more FastPasses available for a ride.
> Fixes #211

- README.md
- lib/disneytokyo/tokyodisneyresortdisneysea.js
- lib/disneytokyo/tokyodisneyresortmagickingdom.js
* Fix TokyoDisneyResort names to have the same pattern than other parks
* Update readme and link to ChronoPass
> TokyoDisneyResort park names

- lib/disneytokyo/disneyTokyoBase.js
- lib/disneytokyo/tokyodisneyresortdisneysea.js
* Adds a new attraction of DisneySea
* Change regex to match all attractions names
> Improve DisneyTokyoBase

- lib/portaventura/portaventura.js
> Improve PortAventura opening hours fetching

- lib/islandh20live/islandh20live.js
An attempt to fix the issues with the currently posted PR to bring this park onto the main branch. Travis just seemed to be upset about location data, so I've gone through and updated that information to match the real data related to IslandH2OLive
> Updated park location information for IslandH20

- lib/merlinparks/altontowers.js
- lib/merlinparks/merlinpark.js
Merlin Parks API has changed slightly.
Alton Towers has a new API key.
Authentication headers have updated (now requiring a few more keys and the current date)
> Fix for Merlin Parks API changes

- lib/cedarfair/cedarfairparkbase.js
- package-lock.json
- package.json
Also replace Cedar Fair opening hours generally, remove old web scraping methods for their nice new API calls.
> Fix Cedar Park Operating Hours

- README.md
LogRide is an app for both iOS and Android which provides access to a constantly growing and updating database of over 17.3k attractions and nearly 700 parks. Users can view park attractions and history, keep track of the number of times they've ridden any attraction, view statistics about their own ride habits, view news articles about attractions and parks they're interested in, and more. 
We recently implemented themeparks to provide wait times and park operating hours for all the parks and attractions that both platforms support.
> Add LogRide to the list of apps that use this repo

- lib/disneyparis/disneylandparismagickingdom.js
- lib/disneyparis/disneylandpariswaltdisneystudios.js
- lib/disneyparis/disneyparisbase.js
- lib/index.js
* See #238
* Moved to a new directory for cleanliness
* Missing opening hours - only ride wait times so far
> Add new Disneyland Paris API

- lib/disneytokyo/disneyTokyoBase.js
> Add facilityCode to TDR wait time meta property

- lib/portaventura/ferrariland.js
- lib/portaventura/portaventura.js
> Fix FerraryLand and Portaventura opening times

- lib/disneyparis/disneylandparismagickingdom.js
- lib/disneyparis/disneylandpariswaltdisneystudios.js
- lib/disneyparis/disneyparisbase.js
> Change language to French for rides

- lib/disneyparis/disneyparisbase.js
* API returns empty list outside of park hours
* Need to iterate over known rides and fill in times where possible
Will test this properly when park is next closed
> Fix Disney Paris wait times when closed

- lib/merlinparks/altontowers.js
> Use Alton Towers' new calendar API

- lib/herschend/dollywood.js
* Dollywood using different Calendar setup in the app than other herschend parks
> Fix for #268 - Dollywood calendar updates

- lib/disneytokyo/disneyTokyoBase.js
I fix the issue #277 .
There ware topics about new api endpoint and simple curl/wget method url in the conversasion, however, I only changed(incremented) api version from existing. 
The code seems to work fine for now. 
Some detailed version up of other apis may remain, but I have ignored in this commit.
If error occurs again, I will attempt to fix in more detail.
thanks.
> Fix wrong api url of TokyoDisneyResort

- lib/disney/couchbaseChannelDisney.js
> Update the Disney Parks with latest CouchBase auth settings.

- lib/disney/shanghaidisneyresort.js
Thank you for your quick fix.
I tested and verified your fix commit, and I found response object structure was wrong.
so I fix it and commit  it.
> [Fix] Incorrect  response  object  structure

- lib/disney/disneylegacyapi.js
- lib/disney/shanghaiData.js
- lib/disney/shanghaidisneyresort.js
> Shanghai Disney Resort API Change

- lib/efteling/eftelingpark.js
Updated implementation. Will need to test when park is open before merging.
> Efteling Park Updates

- lib/bellewaerde/bellewaerde.js
Adding a check if the ride was open or not (If closed : waitTime will be 999), ride operating time was added if the ride has the operating time
> Adding ride operating time & ride closed condition

- lib/bellewaerde/bellewaerde.js
Instead of openingTime and closingTime
> Fix rideOpeningTime and rideClosingTime for Bellewaerde

- lib/heidepark/heidepark.js
HeidePark recently changed their Calendar URL to the UMBRACO one, to match the other merlin parks.
> [~]Fixed Heide Park Calendar URL

- README.md
I've created an Angular website that uses this module (among others) to request data from theme parks. Due to the pandemic and the closure of some parks some data may not be correct but under "normal" circumstances it shows the correct data.
I'm planning to add more parks in the future, but since parks are currently closed, it can be hard to test the functionality.
The code is open source and is located at https://github.com/timyboy12345/Themeparks-Angular
> Added a 4th example website

- lib/asterixpark/asterixpark.js
- lib/mocks/ParcAsterixOpeningHours.mock
- lib/mocks/ParcAsterixWaitTimes.mock
Fix opening hours and waiting time.
⚠️ Ride id changed!
> Update AsterixPark: new API

- lib/hostedPark.js
- lib/schedule.js
Addresses issue #345 Pass through the description which is returned for special events from the themeparks.wiki api
> Addresses #345 pass through the description for special events

- package-lock.json
- package.json
> Fix bug with Ubuntu and themeparks
