Disney/DisneyTokyoBase.js

In #16 mentioned, finally, I funded out what happen of the location check page always say that you need provide your location info.
If the value of "tdrloc" not encoded, sometimes( it would be all day long ) the API work incorrect when get waiting time.

The cookie "tdrloc" value need encode otherwise they wouldn't receive right string

---

Disney/DisneyBase.js
Disney/DisneyTokyoBase.js
SeaWorld/SeaWorldBase.js
SixFlags/SixFlagsBase.js
Universal/UniversalBase.js
Universal/UniversalJapanBase.js
debugView.js
parkBase.js

Consolidate all the network request functions into a single function.
This allows us to debug all the network requests better, since we can now log them all in a readable format.

Use single network request function

---

Disney/DisneyTokyoBase.js

The stop status of ride has three type of Tokyo Disney. The following is the simple description.
1. 運営・公演中止 If you see this status, it's mean that ride was shutdown all day. It will be never turn to active today.
2. 一時運営中止 If the status show this word out, it's mean the ride is temporarily turn off for some reason, it will be open again for few minutes or few hours later(or maybe shutdown all day).
3. 案内終了 Special type ride, like gallery or transportation, this status mean that it's closed.
So, when those status showing up, waitime should be set to -1 and active flag should be false.

Fixed Tokyo Disney wrong waitime

---

.travis.yml

Travis is failing on merely installing libxmljs.
Copying build configuration from libxmljs to try and get project building and unit-testing again successfully.

Attempt to fix Travis build errors

---

.travis.yml
lib/park.js
lib/test.js

"new.target" is used to ensure that the base class cannot be instantiated directly, but this is an ES6 feature new to Node.js v5.0.0 that cannot be transformed directly by Babel v6 (https://github.com/babel/babel/issues/1088) and results in a syntax error in versions of Node.js <5.0.0. This change fixes the issue using this.constructor and ensures that the script properly runs on older versions of Node.js when Babel is used to build the dist files.
This also adjusts the Travis CI Node.JS versions to include Node.JS 4 and 0.12, which are listed as supported in the package.json file.
Fixes #45

Fix syntax error due to use of non-transformable ES6 "new.target"

---

lib/universal/index.js

Universal API's now return wait times greater than one month, added this change to get all available wait times for the next year. 
The API returns all available park opening times and no more so it will only add valid dates to the schedule. 
A minor change but a useful one to be able to see all available opening dates.

Get all universal opening times published for the next year

---

lib/disney/index.js

It is possible for the access token to expire just as it is
retrieved from the cache and then fails during the request.
Prevent this from occurring by indicating to the cache that
the ttl is lower than the actual token ttl.

Prevent access token expiring edge case

---

lib/disneytokyo/index.js

In a very unusual change, the Tokyo Disneyland servers have started rejecting any web requests without the "Connection: Keep-Alive" header.
This may be a server change mistake, or an intentional attempt to stop projects such as this one. I am going to assume it was a mistake for now since this appears to be server-wide and not specifically for the wait times pages, but it will be worth keeping an eye on the Tokyo Disneyland wait time service in the future to be sure.

Fix Tokyo Disneyland

---

lib/efteling/index.js

I work a lot with the data of this park, and this covers all. 'Storing' is 'interruption', and 'inonderhoud' is 'planned maintenance'.

Added all types of ride states to show also downtime on Efteling

---

lib/disney/disneyBuses.js

For resorts that offer multiple transport services (boats, monorails, etc), they're listed on bus stops. Additionally, the status is listed.
Example:
```
[
{
"type": "Monorail",
"status": "Available"
},
{
"type": "Watercraft",
"status": "Available"
}
]
```

[5.0] Add alternative services to bus times

---

lib/disney/shanghaidisneyresort.js

Allows unauthorized HTTPS certificates as ShanghaiDisneyResort uses a self-signed certificate

Fixes ShanghaiDisneyResort

---

lib/http.js

A GET request always contained the question mark symbol even without query strings.
It can have an impact on some bad APIs (as ThorpePark / AltonTowers).
e.g. the second request contains two entries less than the first request:
* https://www.thorpepark.com/Umbraco/Api/Calendar/GetAllOpeningTimes
* https://www.thorpepark.com/Umbraco/Api/Calendar/GetAllOpeningTimes?

Fixes an issue with the HTTP wrapper

---

lib/disneytokyo/disneyTokyoBase.js

Fixes all Tokyo Disney rides coming back as CLOSED (https://github.com/cubehouse/themeparks/issues/231) by adding a fallback for operating status that uses the new "operatings" message in more recent API versions for status.

Uses operatings to get the operating status for Tokyo rides.

---

lib/universal/universalstudiosjapan.js

* Changed to https://spap.usj.co.jp

Fix API URL for Universal Studios Japan

---

README.md
lib/heidepark/heidepark.js
lib/index.js
lib/mocks/heideParkOpeningTimes.mock
lib/mocks/heideParkWaitTimes.mock
package-lock.json

I added the Heidepark API.
This is my first pull-request, please let me know if something is not as you wish :)
All tests and linting passed so far.
Some information about the api and how i implemented it:
Openingtimes:
The API doesent provide the Openingtimes and the App also redirects you to the mobile website. Now the whole calendar page ist parsed by cheerio. I hope this is ok but i know this will generate some work in the future maybe, when Heidepark desides to change their webpage.
Catering:
The API provides opening hours for their restaurants and snack bars via the API, i added it to the waittimes and added the openinghours to the meta property because i didnt know where to provide it. Let me know if theres a better place for that
Special Events:
The API provides some information …

added heidepark

---

lib/disneyparis/disneyparisbase.js

* Don't return invalid "non-rides" with no name
Some rides are returning "???" for their names. These are meet & greets and other non-rides that don't show up properly. We were ignoring these before Disney Paris switched their API, so am returning to ignore them again.

Fix mystery rides in Disney Paris parks

---

lib/http.js

* Sometimes detecting Object/Array doesn't work
* Detect based on constructor name instead, rather than direct pointer to the constructor
Observed when including themeparks in the NodeJS VM.

Fix JSON parsing error in some environments

---

lib/disneytokyo/disneyTokyoBase.js

Hi.
I improved so that DisneyTokyoPark.FetchWaitTimes() can get meta information for fastpass.
Meta information added is as follows:
- fastPassStartTime: start time of using fastpass (HH:MM:SS at localtime)
- fastPassEndTime: end time of using fastpass (HH:MM:SS at localtime)
- fastPassStatus: status of fastpass ticketing.[ TICKETING or TICKETING_END]
And, I also fixed DisneyTokyoPark.FetchWaitTimes() to be fail-safe because sometimes there is no attractionType on a special day.(ex. Mickey's birthday)

Add fetching meta information for fastpass in Tokyo

---

lib/universal/universalislandsofadventure.js
lib/universal/universalparkbase.js
lib/universal/universalstudiosflorida.js

Addresses #291 
Due to social distancing rules, Universal has increased their usage of their virtual line system. It's a similar system to Disney's FastPass+, where you're given the option of multiple "appointments" you can book. Since it's not exactly FastPass, and the fastPass object is used to denote what rides have Express, I simply added the available times via the metadata. Universal supplies a bunch of internal capacity related data with each appointment, but really all we need to know is what the start & end time is for each appointment.
I would think Hollywood will implement a similar system, so I kept that in mind and we can turn on support for Hollywood with a simple option if they do.
I worked on this after-hours, so I'll need to wait until tomorrow to see if the data …

Add virtual line times to Universal

---

lib/disneytokyo/disneyTokyoBase.js

Hi,
On yesterday, Tokyo Disney Resort re-opened. And all attraction's ID have probably been changed.
Specifically, ID on feching facilities(rides) and ID on fetching wait times no longer match. 
So, DisneyTokyoPark.FetchWaitTimes() returns empty now.
we have to use ride.facilityCode when facility links wait times instead of ride.id.
I attempt to fix this problem but I don't know this way is the best.
regards,

Fix for a issue fetching wait times returns empty on TokyoDisney.

---

lib/universal/universalparkbase.js

Pass the received access token TTL to the Cache.Wrap function through a lambda to capture value reference.
Closes #304

fix(universal): properly pass token ttl to cache

---

lib/portaventura/portaventura.js

Still missing the waiting time

Portaventura fix 202107

---

README.md
lib/heidepark/heidepark.js
lib/http.js

I changed the API used by heidepark.js as discussed in [#281](https://github.com/cubehouse/themeparks/issues/281).
I also had to change http.js to set the requestData to null if nether options.data or options.body are provided, as {} would result in an "unauthorised" error.
I improved the readme too, by adding code fencing to allow syntax highlighting, as this improves the readability.
(I hope, I did everything correct, as this is my first real PR ;)

Readd Support for Heidepark as of #281
